# Generated by Django 5.1.4 on 2024-12-31 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='user_game',
            options={'verbose_name': 'Usuario'},
        ),
        migrations.CreateModel(
            name='Ask_friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_game1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend1', to='app.user_game')),
                ('user_game2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend2', to='app.user_game')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user_game1', 'user_game2'), name='unique_friend1')],
            },
        ),
    ]
