# Generated by Django 5.1.4 on 2025-01-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_code_token_date_alter_code_token_token_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='protocol',
            field=models.CharField(default=524102440, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
