# Generated by Django 5.1.4 on 2025-01-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_support_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='area',
            field=models.IntegerField(choices=[(0, 'Login'), (1, 'Conta'), (2, 'Jogo'), (3, 'Pagina não encontrada'), (4, 'Outros')], default=4),
        ),
        migrations.AlterField(
            model_name='support',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
