# Generated by Django 5.1.4 on 2025-01-13 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_support_area_alter_support_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='area',
            field=models.IntegerField(choices=[(0, 'Login'), (1, 'Conta'), (2, 'Jogo'), (3, 'Pagina não encontrada'), (4, 'Solicitação de amizade'), (5, 'Outros')], default=5),
        ),
        migrations.CreateModel(
            name='Game_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('token', models.CharField(max_length=64, unique=True)),
                ('codegame', models.CharField(max_length=10, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tentative', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_game')),
            ],
        ),
    ]
