# Generated by Django 5.1.4 on 2025-01-14 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_support_area_game_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_number',
            name='token',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Game_number_instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('less_more', models.CharField(max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game_number')),
            ],
        ),
    ]
