# Generated by Django 5.1.4 on 2025-01-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_game_number_token_game_number_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_number',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game_number_instance',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game_number',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='game_number_instance',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
