# Generated by Django 5.1.4 on 2025-01-17 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_game_number_correct_game_number_instance_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_number',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
